version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  broker:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    deploy:
      replicas: 3
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CREATE_TOPICS="lfs-progress:1:1,lfs-audit:1:1,lfs-logging:1:1"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
